steps:
  - name: gcr.io/cloud-builders/go
    args: ['test', '-v' ,'./...']
    env: ['PROJECT_ROOT=github.com/xinyinglim/demos/cloudfunc']
    dir: cloudfunc
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'functions'
    - 'deploy'
    - 'HelloWorld'
    - '--trigger-http'
    - '--runtime=go113'
    - '--region'
    - 'asia-east2'
    - '--project=$PROJECT_ID'
    - '--allow-unauthenticated'
    dir: cloudfunc
