steps:
    - name: gcr.io/cloud-builders/docker
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/helloworld:${SHORT_SHA}', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/helloworld:$COMMIT_SHA'] 
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
      - 'run'
      - 'deploy'
      - 'helloworld'
      - '--image'
      - 'gcr.io/$PROJECT_ID/helloworld:$COMMIT_SHA'
      - '--region'
      - 'asia-east1'
      - '--platform'
      - 'managed'
images:
    - 'gcr.io/$PROJECT_ID/helloworld:$COMMIT_SHA'